### ISSUE TITLE
Replace deprecated React lifecycle method componentWillReceiveProps

### ISSUE THREAD

**Issue by mtjn** [react-qr-reader/react-qr-reader#138]
`componentWillReceiveProps` is deprecated and throws an error in react 16.9.0

"Warning: componentWillReceiveProps has been renamed, and is not recommended for use."

c.f. https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by ahmad-reza619** [comment]
Can i open pull request out of this?

**Comment by mtjn** [comment]
> Can i open pull request out of this?

Sure, why not?

**Comment by simmerer** [comment]
I've got a PR ready here: https://github.com/JodusNodus/react-qr-reader/pull/141

**Comment by iamgutz** [comment]
This is still not fixed `componentWillReceiveProps`, the PR #141 was not merged. Any plans on merging or fixing this? :)

**Comment by kadriev-ilyas** [comment]
Hello,
I also ask you to solve this problem. Thank you in advance

**Comment by JodusNodus** [comment]
Will be fixed in next release.
