### ISSUE TITLE
Is this repo still active? No commits in the last 18 months + lots of open PRs

### ISSUE THREAD

**Issue by jeznag** [react-qr-reader/react-qr-reader#182]
I can see there's a few forks including https://github.com/kybarg/react-qr-scanner#readme

Any suggested forks?

**Comment by wesbos** [comment]
Looks like this one is being maintained https://github.com/kybarg/react-qr-scanner

**Comment by KhaosArbiter** [comment]
The above fork seems to have multiple issues with it as well, and the maintainer has said in several locations that for some reason, it's going to be targeting desktop? In light of this, I've forked this as well and will gladly help bring this up to par as my first real work on a public repo.  If anyone wishes to see about getting their existing pull requests over to the below repo, feel free to reach out to me.  It seems like even in it's current state this is still a very good base for a super simple QR Reader implementation for react based projects, and it would be a shame to just let this die, or squander in non-active or private repo forks.

https://github.com/KhaosArbiter/react-qr-reader

**Comment by JonatanSalas** [comment]
We've based our code in this library but then ported everything to use Zxing under the hood which is really better than JsQR. 

The repo is here: https://github.com/BlackBoxVision/react-qr-reader

**Comment by phuhl** [comment]
Hi @JonatanSalas, thanks for taking over. Are there any plans to migrate to react 17 on your fork?

Cheers

**Comment by JonatanSalas** [comment]
Yes, we've intended support for react 17, if you want  you can open a discussion on the repo so we can talk about all the things that needs to be done in order to support it.

**Comment by phuhl** [comment]
This other issue on another fork says, it "should be painless": https://github.com/kybarg/react-qr-scanner/issues/42

The braking chases between 16 and 17 are quite small, indeed. But thorough testing is advised, I guess

**Comment by chaitanyaarige** [comment]
yes there is a PR which is working and most of the people have found a workaround.
https://github.com/JodusNodus/react-qr-reader/pull/192

But the above mentioned react-qr-reader has duplicate dependencies, which is not good. better avoid for dependencies.

**Comment by JonatanSalas** [comment]
@chaitanyaarige at https://github.com/BlackBoxVision/react-qr-reader we've added support for React v17.

**Comment by chaitanyaarige** [comment]
Thanks a lot for your good work

**Comment by JodusNodus** [comment]
Working on the new release thanks to the work of @JonatanSalas.
