### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

### ISSUE THREAD

**Issue by Mediacannibal** [react-qr-reader/react-qr-reader#186]
[Warning] Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details. (vendors~main.js, line 30676)

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Reader

**Comment by KhaosArbiter** [comment]
Please, if you are interested, I have forked this project for proper maintenance over at the below repo.  We are working on this and other issues open on this repo slowly but surely.

 https://github.com/KhaosArbiter/modern-react-qr-reader

**Comment by nastassiadanilova** [comment]
dublicates https://github.com/JodusNodus/react-qr-reader/issues/138 https://github.com/JodusNodus/react-qr-reader/issues/149

**Comment by JodusNodus** [comment]
Will be fixed in next release.
