### ISSUE TITLE
Provide a way for the QrReader control to give some feedback when QR codes are detected.

### ISSUE THREAD

**Issue by howech** [react-qr-reader/react-qr-reader#217]
I am using react-qr-reader in a project that used animated QR codes. It would be really nice if I were able to give my users some feedback showing when and where the reader has detected a QR code in the image. 

In other tools, I have seen this feedback come in the form of a rectangle drawn around the detected QR code displayed to the user. Furthermore, I have found that when scanning a long sequence (20-ish images) that this kind of feedback is valuable to the user as it helps them to keep the camera steady for the duration of the scan.

**Comment by JodusNodus** [comment]
Good feedback. I'll add it to the board.
